# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: calculate.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='calculate.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0f\x63\x61lculate.proto\"e\n\x19\x43\x61lculateSomethingRequest\x12\x0f\n\x07numbers\x18\x01 \x03(\x05\x12&\n\x0eoperation_type\x18\x02 \x01(\x0e\x32\x0e.OperationType\x12\x0f\n\x07\x64ivider\x18\x03 \x01(\x05\"T\n\x1a\x43\x61lculateSomethingResponse\x12\x0e\n\x06result\x18\x01 \x01(\x05\x12&\n\x0eoperation_type\x18\x02 \x01(\x0e\x32\x0e.OperationType*.\n\rOperationType\x12\x0b\n\x07UNKNOWN\x10\x00\x12\x07\n\x03\x41\x44\x44\x10\x01\x12\x07\n\x03MUL\x10\x02\x32\x63\n\x10\x43\x61lculateService\x12O\n\x12\x43\x61lculateSomething\x12\x1a.CalculateSomethingRequest\x1a\x1b.CalculateSomethingResponse\"\x00\x62\x06proto3'
)

_OPERATIONTYPE = _descriptor.EnumDescriptor(
  name='OperationType',
  full_name='OperationType',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='UNKNOWN', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='ADD', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='MUL', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=208,
  serialized_end=254,
)
_sym_db.RegisterEnumDescriptor(_OPERATIONTYPE)

OperationType = enum_type_wrapper.EnumTypeWrapper(_OPERATIONTYPE)
UNKNOWN = 0
ADD = 1
MUL = 2



_CALCULATESOMETHINGREQUEST = _descriptor.Descriptor(
  name='CalculateSomethingRequest',
  full_name='CalculateSomethingRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='numbers', full_name='CalculateSomethingRequest.numbers', index=0,
      number=1, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='operation_type', full_name='CalculateSomethingRequest.operation_type', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='divider', full_name='CalculateSomethingRequest.divider', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=19,
  serialized_end=120,
)


_CALCULATESOMETHINGRESPONSE = _descriptor.Descriptor(
  name='CalculateSomethingResponse',
  full_name='CalculateSomethingResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='result', full_name='CalculateSomethingResponse.result', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='operation_type', full_name='CalculateSomethingResponse.operation_type', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=122,
  serialized_end=206,
)

_CALCULATESOMETHINGREQUEST.fields_by_name['operation_type'].enum_type = _OPERATIONTYPE
_CALCULATESOMETHINGRESPONSE.fields_by_name['operation_type'].enum_type = _OPERATIONTYPE
DESCRIPTOR.message_types_by_name['CalculateSomethingRequest'] = _CALCULATESOMETHINGREQUEST
DESCRIPTOR.message_types_by_name['CalculateSomethingResponse'] = _CALCULATESOMETHINGRESPONSE
DESCRIPTOR.enum_types_by_name['OperationType'] = _OPERATIONTYPE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

CalculateSomethingRequest = _reflection.GeneratedProtocolMessageType('CalculateSomethingRequest', (_message.Message,), {
  'DESCRIPTOR' : _CALCULATESOMETHINGREQUEST,
  '__module__' : 'calculate_pb2'
  # @@protoc_insertion_point(class_scope:CalculateSomethingRequest)
  })
_sym_db.RegisterMessage(CalculateSomethingRequest)

CalculateSomethingResponse = _reflection.GeneratedProtocolMessageType('CalculateSomethingResponse', (_message.Message,), {
  'DESCRIPTOR' : _CALCULATESOMETHINGRESPONSE,
  '__module__' : 'calculate_pb2'
  # @@protoc_insertion_point(class_scope:CalculateSomethingResponse)
  })
_sym_db.RegisterMessage(CalculateSomethingResponse)



_CALCULATESERVICE = _descriptor.ServiceDescriptor(
  name='CalculateService',
  full_name='CalculateService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=256,
  serialized_end=355,
  methods=[
  _descriptor.MethodDescriptor(
    name='CalculateSomething',
    full_name='CalculateService.CalculateSomething',
    index=0,
    containing_service=None,
    input_type=_CALCULATESOMETHINGREQUEST,
    output_type=_CALCULATESOMETHINGRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_CALCULATESERVICE)

DESCRIPTOR.services_by_name['CalculateService'] = _CALCULATESERVICE

# @@protoc_insertion_point(module_scope)
