# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: calculate.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='calculate.proto',
  package='',
  syntax='proto2',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0f\x63\x61lculate.proto\"j\n\x19\x43\x61lculateSomethingRequest\x12\x0f\n\x07numbers\x18\x01 \x03(\x05\x12+\n\x0eoperation_type\x18\x02 \x01(\x0e\x32\x0e.OperationType:\x03MUL\x12\x0f\n\x07\x64ivider\x18\x03 \x02(\x05\"\xf3\x02\n\x1a\x43\x61lculateSomethingResponse\x12S\n\x0cvalid_result\x18\x01 \x01(\x0b\x32;.CalculateSomethingResponse.CalculateSomethingResponseValidH\x00\x12W\n\x0einvalid_result\x18\x02 \x01(\x0b\x32=.CalculateSomethingResponse.CalculateSomethingResponseInvalidH\x00\x1aY\n\x1f\x43\x61lculateSomethingResponseValid\x12\x0e\n\x06result\x18\x01 \x02(\x05\x12&\n\x0eoperation_type\x18\x02 \x02(\x0e\x32\x0e.OperationType\x1a\x42\n!CalculateSomethingResponseInvalid\x12\x0c\n\x04\x63ode\x18\x01 \x02(\x05\x12\x0f\n\x07message\x18\x02 \x01(\tB\x08\n\x06result*!\n\rOperationType\x12\x07\n\x03\x41\x44\x44\x10\x00\x12\x07\n\x03MUL\x10\x01\x32\x61\n\x10\x43\x61lculateService\x12M\n\x12\x43\x61lculateSomething\x12\x1a.CalculateSomethingRequest\x1a\x1b.CalculateSomethingResponse'
)

_OPERATIONTYPE = _descriptor.EnumDescriptor(
  name='OperationType',
  full_name='OperationType',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='ADD', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='MUL', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=501,
  serialized_end=534,
)
_sym_db.RegisterEnumDescriptor(_OPERATIONTYPE)

OperationType = enum_type_wrapper.EnumTypeWrapper(_OPERATIONTYPE)
ADD = 0
MUL = 1



_CALCULATESOMETHINGREQUEST = _descriptor.Descriptor(
  name='CalculateSomethingRequest',
  full_name='CalculateSomethingRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='numbers', full_name='CalculateSomethingRequest.numbers', index=0,
      number=1, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='operation_type', full_name='CalculateSomethingRequest.operation_type', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=True, default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='divider', full_name='CalculateSomethingRequest.divider', index=2,
      number=3, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=19,
  serialized_end=125,
)


_CALCULATESOMETHINGRESPONSE_CALCULATESOMETHINGRESPONSEVALID = _descriptor.Descriptor(
  name='CalculateSomethingResponseValid',
  full_name='CalculateSomethingResponse.CalculateSomethingResponseValid',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='result', full_name='CalculateSomethingResponse.CalculateSomethingResponseValid.result', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='operation_type', full_name='CalculateSomethingResponse.CalculateSomethingResponseValid.operation_type', index=1,
      number=2, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=332,
  serialized_end=421,
)

_CALCULATESOMETHINGRESPONSE_CALCULATESOMETHINGRESPONSEINVALID = _descriptor.Descriptor(
  name='CalculateSomethingResponseInvalid',
  full_name='CalculateSomethingResponse.CalculateSomethingResponseInvalid',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='code', full_name='CalculateSomethingResponse.CalculateSomethingResponseInvalid.code', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='message', full_name='CalculateSomethingResponse.CalculateSomethingResponseInvalid.message', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=423,
  serialized_end=489,
)

_CALCULATESOMETHINGRESPONSE = _descriptor.Descriptor(
  name='CalculateSomethingResponse',
  full_name='CalculateSomethingResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='valid_result', full_name='CalculateSomethingResponse.valid_result', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='invalid_result', full_name='CalculateSomethingResponse.invalid_result', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_CALCULATESOMETHINGRESPONSE_CALCULATESOMETHINGRESPONSEVALID, _CALCULATESOMETHINGRESPONSE_CALCULATESOMETHINGRESPONSEINVALID, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='result', full_name='CalculateSomethingResponse.result',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=128,
  serialized_end=499,
)

_CALCULATESOMETHINGREQUEST.fields_by_name['operation_type'].enum_type = _OPERATIONTYPE
_CALCULATESOMETHINGRESPONSE_CALCULATESOMETHINGRESPONSEVALID.fields_by_name['operation_type'].enum_type = _OPERATIONTYPE
_CALCULATESOMETHINGRESPONSE_CALCULATESOMETHINGRESPONSEVALID.containing_type = _CALCULATESOMETHINGRESPONSE
_CALCULATESOMETHINGRESPONSE_CALCULATESOMETHINGRESPONSEINVALID.containing_type = _CALCULATESOMETHINGRESPONSE
_CALCULATESOMETHINGRESPONSE.fields_by_name['valid_result'].message_type = _CALCULATESOMETHINGRESPONSE_CALCULATESOMETHINGRESPONSEVALID
_CALCULATESOMETHINGRESPONSE.fields_by_name['invalid_result'].message_type = _CALCULATESOMETHINGRESPONSE_CALCULATESOMETHINGRESPONSEINVALID
_CALCULATESOMETHINGRESPONSE.oneofs_by_name['result'].fields.append(
  _CALCULATESOMETHINGRESPONSE.fields_by_name['valid_result'])
_CALCULATESOMETHINGRESPONSE.fields_by_name['valid_result'].containing_oneof = _CALCULATESOMETHINGRESPONSE.oneofs_by_name['result']
_CALCULATESOMETHINGRESPONSE.oneofs_by_name['result'].fields.append(
  _CALCULATESOMETHINGRESPONSE.fields_by_name['invalid_result'])
_CALCULATESOMETHINGRESPONSE.fields_by_name['invalid_result'].containing_oneof = _CALCULATESOMETHINGRESPONSE.oneofs_by_name['result']
DESCRIPTOR.message_types_by_name['CalculateSomethingRequest'] = _CALCULATESOMETHINGREQUEST
DESCRIPTOR.message_types_by_name['CalculateSomethingResponse'] = _CALCULATESOMETHINGRESPONSE
DESCRIPTOR.enum_types_by_name['OperationType'] = _OPERATIONTYPE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

CalculateSomethingRequest = _reflection.GeneratedProtocolMessageType('CalculateSomethingRequest', (_message.Message,), {
  'DESCRIPTOR' : _CALCULATESOMETHINGREQUEST,
  '__module__' : 'calculate_pb2'
  # @@protoc_insertion_point(class_scope:CalculateSomethingRequest)
  })
_sym_db.RegisterMessage(CalculateSomethingRequest)

CalculateSomethingResponse = _reflection.GeneratedProtocolMessageType('CalculateSomethingResponse', (_message.Message,), {

  'CalculateSomethingResponseValid' : _reflection.GeneratedProtocolMessageType('CalculateSomethingResponseValid', (_message.Message,), {
    'DESCRIPTOR' : _CALCULATESOMETHINGRESPONSE_CALCULATESOMETHINGRESPONSEVALID,
    '__module__' : 'calculate_pb2'
    # @@protoc_insertion_point(class_scope:CalculateSomethingResponse.CalculateSomethingResponseValid)
    })
  ,

  'CalculateSomethingResponseInvalid' : _reflection.GeneratedProtocolMessageType('CalculateSomethingResponseInvalid', (_message.Message,), {
    'DESCRIPTOR' : _CALCULATESOMETHINGRESPONSE_CALCULATESOMETHINGRESPONSEINVALID,
    '__module__' : 'calculate_pb2'
    # @@protoc_insertion_point(class_scope:CalculateSomethingResponse.CalculateSomethingResponseInvalid)
    })
  ,
  'DESCRIPTOR' : _CALCULATESOMETHINGRESPONSE,
  '__module__' : 'calculate_pb2'
  # @@protoc_insertion_point(class_scope:CalculateSomethingResponse)
  })
_sym_db.RegisterMessage(CalculateSomethingResponse)
_sym_db.RegisterMessage(CalculateSomethingResponse.CalculateSomethingResponseValid)
_sym_db.RegisterMessage(CalculateSomethingResponse.CalculateSomethingResponseInvalid)



_CALCULATESERVICE = _descriptor.ServiceDescriptor(
  name='CalculateService',
  full_name='CalculateService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=536,
  serialized_end=633,
  methods=[
  _descriptor.MethodDescriptor(
    name='CalculateSomething',
    full_name='CalculateService.CalculateSomething',
    index=0,
    containing_service=None,
    input_type=_CALCULATESOMETHINGREQUEST,
    output_type=_CALCULATESOMETHINGRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_CALCULATESERVICE)

DESCRIPTOR.services_by_name['CalculateService'] = _CALCULATESERVICE

# @@protoc_insertion_point(module_scope)
