# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import stream.grpcGen.calculate_stream_pb2 as calculate__stream__pb2


class CalculateServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CalculateSomething = channel.stream_stream(
                '/calculate_stream.CalculateService/CalculateSomething',
                request_serializer=calculate__stream__pb2.CalculateSomethingRequest.SerializeToString,
                response_deserializer=calculate__stream__pb2.CalculateSomethingResponse.FromString,
                )


class CalculateServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CalculateSomething(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CalculateServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CalculateSomething': grpc.stream_stream_rpc_method_handler(
                    servicer.CalculateSomething,
                    request_deserializer=calculate__stream__pb2.CalculateSomethingRequest.FromString,
                    response_serializer=calculate__stream__pb2.CalculateSomethingResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'calculate_stream.CalculateService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class CalculateService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CalculateSomething(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(request_iterator, target, '/calculate_stream.CalculateService/CalculateSomething',
            calculate__stream__pb2.CalculateSomethingRequest.SerializeToString,
            calculate__stream__pb2.CalculateSomethingResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
